<section class="vh-100 mt-5">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form action="<?= App::config('url') ?>login/authorize" method="POST">
                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <label class="form-label" for="email">Email address</label>
                        <input type="email" name="email" id="email" class="form-control form-control-lg" value="<?=$email;?>"/>
                        <?php if ($message->email != ''):?>
                            <small id="emailHelp" class="form-text text-muted"><?= $message->email; ?></small>
                        <?php else:?>
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        <?php endif;?>
                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-3">
                        <label class="form-label" for="password">Password</label>
                        <input type="password" name="password" id="password" class="form-control form-control-lg"/>
                        <?php if ($message->password != ''):?>
                            <small id="emailHelp" class="form-text text-muted"><?= $message->password; ?></small>
                        <?php endif;?>
                    </div>


                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Checkbox -->
                        <div class="form-check mb-0">
                            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                            <label class="form-check-label" for="form2Example3">
                                Remember me
                            </label>
                        </div>
                    </div>
                    <div class="text-center text-lg-start mt-4 pt-2">
                        <input type="submit" class="btn btn-primary btn-lg"
                                style="padding-left: 2.5rem; padding-right: 2.5rem;" value="Login"/>
                        <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="<?=App::config('url');?>registration"
                                                                                          class="link-danger">Register</a></p>
                    </div>

                </form>
            </div>
        </div>
    </div>

</section>